### ISSUE TITLE
Paper requirement

### ISSUE THREAD

**Issue by mb-Ma** [andresC98/TSF_Transformers_TFM#1]
Hi, 
First, this is a solid work and I am focusing on this research. Could you provide your master thesis to my email (minboma@my.swjtu.edu.cn) or related academic paper? 

Thanks.

**Comment by andresC98** [comment]
Hi sir, first of all thank you very much for your interest! I have just send the thesis to your email.

**Comment by hajarmerbouh** [comment]
hello @andresC98 , can you provide it to me too? here is my email : merbouhajar091@gmail.com . thank you in advance :)

**Comment by andresC98** [comment]
> hello @andresC98 , can you provide it to me too? here is my email : [merbouhajar091@gmail.com](mailto:merbouhajar091@gmail.com) . thank you in advance :)

I have just sent it to your email! (Apologies for the late response).
