### ISSUE TITLE
Computing Infrastructure

### ISSUE THREAD

**Issue by CSEE01** [andresC98/TSF_Transformers_TFM#2]
Hi Andres,

Thank you for your interesting work! Could you please give us more details on the hardware used during training (GPU type, RAM size)? Did you use free google Colab or Colab Pro? 

Thank you.

**Comment by andresC98** [comment]
Hi, thank you very much for your interest on the project! I used the free tier of Google Colab for the entire development of this project. 

I really hope it helps you on your research/work.

Best,
Andrés.

**Comment by saraLamay** [comment]
Thank you for the feedback. But how much was approximately the training time for the TFT and Informer model?

**Comment by CSEE01** [comment]
Thank you for the feedback.
